[package]
name = "bls_shamir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = { version="0.6.0", features=["experimental"] }
group = "0.11.0"
sha2 = "0.9.0"